---
- name: Setup Rabbitmq repo
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash

- name: Install rabbitmq
  apt: name={{ item }} state=installed
  with_items:
  - rabbitmq-server
  - vim 
