---
- name: Setup Rabbitmq repo
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash

- name: Install rabbitmq
  apt: name={{ item }} state=present
  with_items:
  - rabbitmq-server
  - vim 

- name: Enables the rabbitmq_management plugin
  community.rabbitmq.rabbitmq_plugin:
    names: rabbitmq_management
    state: disabled