---
- name: Setup Rabbitmq repo
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash

- name: Install rabbitmq
  apt: name={{ item }} state=present
  with_items:
  - rabbitmq-server
  - vim 

- name: Enables the rabbitmq_management plugin
  shell: rabbitmq-plugins enable rabbitmq_management


 - name: Add and configure management user
    shell: |
      rabbitmqctl add_user "admin" "Test12"
      rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
      rabbitmqctl set_user_tags admin administrator      